In [ ]:
!pip install tabula-py

Collecting tabula-py
  Downloading tabula_py-2.7.0-py3-none-any.whl (12.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 65.2 MB/s eta 0:00:00
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.10/dist-packages (from tabula-py) (1.5.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from tabula-py) (1.22.4)
Requirement already satisfied: distro in /usr/lib/python3/dist-packages (from tabula-py) (1.7.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.25.3->tabula-py) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.25.3->tabula-py) (2022.7.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas>=0.25.3->tabula-py) (1.16.0)
Installing collected packages: tabula-py
Successfully installed tabula-py-2.7.0

## <font color=Yellow>Importando as Tabelas dos Pdfs

### Tabula, Try e while ...

In [ ]:
import tabula #Ferramenta para extrair dados de tabelas em arquivos PDF.


def extrair_tabela_do_pdf(caminho_pdf, pagina): #Define uma função chamada extrair_tabela_do_pdf que recebe dois parâmetros:

    try: #Inicia um bloco de código onde o programa tentará executar o código dentro do bloco e tratará possíveis exceções (erros)
        dados = tabula.read_pdf(caminho_pdf, pages=pagina)[0]
        return dados
    except Exception as e:
        print("Erro ao extrair tabela:", e)
        return None






contador = 8
while contador <= 13: #Loop que estipula que enquanto contador for menor que 13 vai rodar o código dentro da identação
        caminho_pdf = "copax1_" + str(contador) + ".pdf" # Caminho fica: copax1_8.pdf...copax1_9.pdf... copax1_10.pdf...
        pagina = 1    #Referente á pagina


        dados = extrair_tabela_do_pdf(caminho_pdf, pagina)  #Extrai a tabela do pdf (parametros:caminho do pdf, página)

        if dados is not None:       #Se os dados é diferente de nada ...
            caminho_csv = f"dados_copa_{contador}.csv"  # Defina um nome mais significativo para o arquivo CSV
            dados.to_csv(caminho_csv, index=False, sep=';')
            print(f"Tabela do arquivo {caminho_pdf} salva como CSV em {caminho_csv}.")
        else:
            print(f"Não foi possível extrair a tabela do arquivo {caminho_pdf}.")  # #Se os dados é não for diferente de nada ...

        contador += 1   #Enquanto contador for menor que 13 adiciona mais 1

Erro ao extrair tabela: [Errno 2] No such file or directory: 'copax1_8.pdf'
Não foi possível extrair a tabela do arquivo copax1_8.pdf.
Erro ao extrair tabela: [Errno 2] No such file or directory: 'copax1_9.pdf'
Não foi possível extrair a tabela do arquivo copax1_9.pdf.
Erro ao extrair tabela: [Errno 2] No such file or directory: 'copax1_10.pdf'
Não foi possível extrair a tabela do arquivo copax1_10.pdf.
Erro ao extrair tabela: [Errno 2] No such file or directory: 'copax1_11.pdf'
Não foi possível extrair a tabela do arquivo copax1_11.pdf.
Erro ao extrair tabela: [Errno 2] No such file or directory: 'copax1_12.pdf'
Não foi possível extrair a tabela do arquivo copax1_12.pdf.
Erro ao extrair tabela: [Errno 2] No such file or directory: 'copax1_13.pdf'
Não foi possível extrair a tabela do arquivo copax1_13.pdf.

### Salvando os Dataframes na memória

In [ ]:
import pandas as pd

contador = 9
caminho_csv = "dados_copax1_" + str(contador) + ".csv"
dados = {}

# Carregar o arquivo CSV e armazenar no dicionário usando a chave "dados_8" (ou outro valor de contador)
dados["dados_" + str(contador)] = pd.read_csv(caminho_csv, sep=';')

# Agora você pode acessar o DataFrame usando a chave "dados_8" (ou outro valor de contador)
print(dados["dados_" + str(contador)])

<font color=yellow> Se você deseja carregar os dados do arquivo CSV e atribuí-los a uma variável com base no valor de contador, uma maneira adequada de fazer isso é usando um dicionário. Os dicionários em Python permitem associar chaves (nomes) a valores. Nesse caso, podemos usar as chaves para representar os diferentes DataFrames.

In [ ]:
#Jeito manual de se salvar os dataframes na memória

contador = 13
caminho_csv = "dados_copax1_" + str(contador) + ".csv"
dados_13 = pd.read_csv(caminho_csv, sep=';')
print(dados_13)

### Concatenando os Dataframes

In [ ]:
 dados_gerais = pd.concat([dados_3, dados_4, dados_5, dados_6, dados_7, dados_8, dados_9, dados_10, dados_11, dados_12, dados_13 ])
 dados_gerais

### Salvar em Excel

In [ ]:
# Usando to_excel() para salvar o DataFrame em um arquivo Excel
dados_gerais.to_excel("Dados_Gerais.xlsx", sheet_name="Dados_Gerais")

## <font color = yellow>Tratamento de dados

In [ ]:
import pandas as pd
dados = pd.read_excel("Dados_Gerais.xlsx")
dados.columns = ["Retirar", "Pos", "Equipe", "Pontos", "Jogos", "Vitorias", "Empates", "Derrotas", "GP", "GC", "SG", "Porc" ]  #Renomeia as colunas
dados = dados.drop("Retirar", axis=1)  #Tirar coluna extra

###Tratando dados nulosn e Convertendo tipos de daos.

In [ ]:
dados.info()      #Exibir informações básicas do DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pos       143 non-null    object
 1   Equipe    146 non-null    object
 2   Pontos    143 non-null    object
 3   Jogos     144 non-null    object
 4   Vitorias  123 non-null    float64
 5   Empates   143 non-null    object
 6   Derrotas  143 non-null    object
 7   GP        143 non-null    object
 8   GC        143 non-null    object
 9   SG        123 non-null    float64
 10  Porc      143 non-null    object
dtypes: float64(2), object(9)
memory usage: 13.0+ KB

In [ ]:
# Tratamento de valores ausentes
# Preencher valores ausentes com zero
dados.fillna(0, inplace=True)

In [ ]:
dados["Pos"] = dados["Pos"].astype(int)      #Converter tipos de colunas
dados["Pontos"] = dados["Pontos"].astype(int)
dados["Jogos"] = dados["Jogos"].astype(int)
dados["Vitorias"] = dados["Vitorias"].astype(int)
dados["Empates"] = dados["Empates"].astype(int)
dados[ "Derrotas"] = dados["Derrotas"].astype(int)
dados["GP"] = dados["GP"].astype(int)
dados["GC"] = dados["GC"].astype(int)
dados["SG" ] = dados["SG"].astype(int)
dados[ "Porc" ] = dados[ "Porc"].astype(int)


#O erro ValueError indica que a conversão para o tipo int falhou porque uma das colunas contém valores não numéricos.
# O valor 'P' está causando o problema, já que não pode ser convertido para um número inteiro.
#Para lidar com isso, é necessário identificar quais são os valores não numéricos que estão causando o problema.
#Uma opção é imprimir os valores únicos na coluna problemática para entender quais são esses valores. Aqui está um exemplo:

In [ ]:
dados['Pos'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  0, 13, 14, 15, 16])

In [ ]:
# Conversão das colunas para o tipo int
dados["Pos"] = pd.to_numeric(dados["Pos"], errors="coerce").fillna(0).astype(int)
# Ao definir errors="coerce", qualquer valor que não possa ser convertido para numérico será substituído por NaN.
# Em seguida, usamos fillna(0) para substituir os NaNs por zero, garantindo que os valores não numéricos sejam tratados como zero.
# Usamos astype(int) para converter os valores restantes para o tipo inteiro

dados.info()

In [ ]:
dados['Pos'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  0, 13, 14, 15, 16])

In [ ]:
dados["Pos"] = dados["Pos"].astype(int)   # "Pos" agora está convertido a números inteiros, faça com todos que for necessários
dados.info()

In [ ]:
dados["Pontos"] = pd.to_numeric(dados["Pontos"], errors="coerce").fillna(0).astype(int)
dados["Vitorias"] = pd.to_numeric(dados["Vitorias"], errors="coerce").fillna(0).astype(int)
dados["Jogos"] = pd.to_numeric(dados["Jogos"], errors="coerce").fillna(0).astype(int)
dados["Empates"] = pd.to_numeric(dados["Empates"], errors="coerce").fillna(0).astype(int)
dados["Derrotas"] = pd.to_numeric(dados["Derrotas"], errors="coerce").fillna(0).astype(int)
dados["GP"] = pd.to_numeric(dados["GP"], errors="coerce").fillna(0).astype(int)
dados["GC"] = pd.to_numeric(dados["GC"], errors="coerce").fillna(0).astype(int)
dados["SG"] = pd.to_numeric(dados["SG"], errors="coerce").fillna(0).astype(float)
dados["Porc"] = pd.to_numeric(dados["Porc"], errors="coerce").fillna(0).astype(float)
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pos       150 non-null    int64
 1   Equipe    150 non-null    object
 2   Pontos    150 non-null    int64
 3   Jogos     150 non-null    int64
 4   Vitorias  150 non-null    int64
 5   Empates   150 non-null    int64
 6   Derrotas  150 non-null    int64
 7   GP        150 non-null    int64
 8   GC        150 non-null    int64
 9   SG        150 non-null    float64
 10  Porc      150 non-null    float64
dtypes: float64(2), int64(8), object(1)
memory usage: 13.0+ KB

In [ ]:
dados.to_csv('dados_tratados.csv', index=False)

In [ ]:
dados_tratados = pd.read_csv('dados_tratados.csv')
dados_tratados

,Pos,Equipe,Pontos,Jogos,Vitorias,Empates,Derrotas,GP,GC,SG,Porc
0,1,Vitin/Ceara,26,11,8,2,1,32,17,15.0,79.0
1,2,Eric/Santos,24,11,7,3,1,27,12,15.0,73.0
2,3,Barone/Vasco,21,11,6,3,2,32,20,12.0,64.0
3,4,Douglas/Fluminense,20,11,6,2,3,29,24,5.0,61.0
4,5,Icaro/CAP,19,11,5,4,2,25,14,11.0,58.0
...,...,...,...,...,...,...,...,...,...,...,...
145,6,Israel/Bahia,15,18,0,0,4,2,11,0.0,28.0
146,7,Pedro2/Samp_Corr,6,18,0,0,11,4,33,0.0,11.0
147,8,Vitin/Londrina,3,18,0,0,12,5,11,0.0,6.0
148,9,Cicero/Criciuma,0,18,0,0,12,0,6,0.0,0.0
149,10,Douglas/Corinthians,0,18,0,0,9,0,24,0.0,0.0

Ainda se necessário, pode-se remover duplicatas, Tratar dados categóricos etc.

In [ ]:
dados_tratados.to_excel('dados_tratados.xlsx')

###<font color=yellow>Categorizando os dados

In [ ]:
# Usar a função str.contains() para selecionar as linhas onde o valor da coluna "Equipe" contém "icaro" (ignorando maiúsculas/minúsculas)
Icaro = dados_tratados.query('Equipe.str.contains("icaro", case=False)', engine='python')
Jogos = Icaro['Jogos'].sum()
Vitorias = Icaro['Vitorias'].sum()
Empates = Icaro['Empates'].sum()
Derrotas = Icaro['Derrotas'].sum()
print(Jogos)
print(Vitorias)
print(Empates)
print(Derrotas)

In [ ]:
# Definindo a variável 'player' com o nome do jogador
player = "icaro"

Dados_Individuais = dados_tratados.query('Equipe.str.contains(@player, case=False)', engine='python')
# 'Equipe.str.contains(@player, case=False)': É a condição da consulta.
#...Neste caso, estamos usando a função str.contains() para verificar se o valor da coluna "Equipe" contém a string contida na variável player.
#O parâmetro case=False indica que a pesquisa deve ser feita ignorando maiúsculas/minúsculas, ou seja, a pesquisa é case-insensitive.
#engine='python': Esse parâmetro especifica o mecanismo de consulta a ser usado. Neste caso, estamos usando o mecanismo de consulta em Python.


# Calculando as somas
Jogos = Dados_Individuais['Jogos'].sum()
Vitorias = Dados_Individuais['Vitorias'].sum()
Empates = Dados_Individuais['Empates'].sum()
Derrotas = Dados_Individuais['Derrotas'].sum()

# Convertendo as variáveis numéricas em strings antes de concatená-las com outras strings
print("Número de jogos do " + player + " é " + str(Jogos))
print("Número de Vitórias do " + player + " é " + str(Vitorias))
print("Número de Empates do " + player + " é " + str(Empates))
print("Número de Derrotas do " + player + " é " + str(Derrotas))

Número de jogos do icaro é 115
Número de Vitórias do icaro é 47
Número de Empates do icaro é 27
Número de Derrotas do icaro é 29

In [ ]:
jaison = dados_tratados.query('Equipe.str.contains("jaison", case=False)', engine='python')
jaison

,Pos,Equipe,Pontos,Jogos,Vitorias,Empates,Derrotas,GP,GC,SG,Porc
65,12,Jaison/Shaktar,8,11,2,2,7,11,23,-12.0,24.0
69,4,JAISON/PAOK,25,13,8,1,4,26,19,7.0,64.0
87,4,Jaison/IRAQUE,27,15,8,3,4,31,22,9.0,60.0
106,5,Jaison/Napoli,11,11,3,2,2,15,13,2.0,33.0
128,15,Jaison/Paok,0,15,0,0,12,0,36,-36.0,0.0
141,2,Jaison/CSA,40,18,0,1,4,31,15,0.0,74.0